# Generated by Django 4.2.5 on 2023-09-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.FileField(blank=True, null=True, upload_to='produtos/'),
        ),
    ]
